import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const dummyStudents = [
  {
    timestamp: '2024-03-01 10:15:30',
    emailAddress: 'rahul.sharma@example.com',
    fullName: 'Rahul Sharma',
    gender: 'Male',
    dob: '2002-05-14',
    contactNumber: '+91 98765 43210',
    emailId: 'rahul.sharma@example.com',
    registrationNo: 'REG-2024-001',
    college: 'IIIT Jabalpur',
    course: 'B.Tech',
    passingYear: 2025,
    specialization: 'Computer Science and Engineering',
    class10Percentage: 92.4,
    class12Percentage: 89.6,
    graduationCGPA: 8.75,
    activeBacklogs: false,
    activeBacklogsRaw: 'No',
    resumeUrl: 'https://example.com/resumes/rahul_sharma.pdf',
    stage: 'Stage 2',
    comments: [
      'Strong DSA problem solving fundamentals.',
      'Cleared technical round 1 with high marks in system design basics.',
    ],
  },
  {
    timestamp: '2024-03-01 11:20:10',
    emailAddress: 'priya.patel@example.com',
    fullName: 'Priya Patel',
    gender: 'Female',
    dob: '2003-08-22',
    contactNumber: '+91 98765 43211',
    emailId: 'priya.patel@example.com',
    registrationNo: 'REG-2024-002',
    college: 'NIT Trichy',
    course: 'B.Tech',
    passingYear: 2025,
    specialization: 'Computer Science and Engineering',
    class10Percentage: 96.0,
    class12Percentage: 94.2,
    graduationCGPA: 9.35,
    activeBacklogs: false,
    activeBacklogsRaw: 'No',
    resumeUrl: 'https://example.com/resumes/priya_patel.pdf',
    stage: 'Selected',
    comments: [
      'Exceptional coding skills and communication.',
      'Final HR round cleared. Offer letter recommended.',
    ],
  },
  {
    timestamp: '2024-03-01 12:05:44',
    emailAddress: 'aman.verma@example.com',
    fullName: 'Aman Verma',
    gender: 'Male',
    dob: '2001-11-03',
    contactNumber: '+91 98765 43212',
    emailId: 'aman.verma@example.com',
    registrationNo: 'REG-2024-003',
    college: 'IIT Delhi',
    course: 'B.Tech',
    passingYear: 2024,
    specialization: 'Information Technology',
    class10Percentage: 85.5,
    class12Percentage: 82.0,
    graduationCGPA: 7.42,
    activeBacklogs: true,
    activeBacklogsRaw: 'Yes (1 subject)',
    resumeUrl: 'https://example.com/resumes/aman_verma.pdf',
    stage: 'Stage 1',
    comments: [
      'Good web development projects using Next.js and Go.',
      'Discussed active backlog in mathematics, planning to clear next semester.',
    ],
  },
  {
    timestamp: '2024-03-02 09:30:15',
    emailAddress: 'sneha.reddy@example.com',
    fullName: 'Sneha Reddy',
    gender: 'Female',
    dob: '2002-02-18',
    contactNumber: '+91 98765 43213',
    emailId: 'sneha.reddy@example.com',
    registrationNo: 'REG-2024-004',
    college: 'BITS Pilani',
    course: 'B.E.',
    passingYear: 2025,
    specialization: 'Electronics and Communication',
    class10Percentage: 94.8,
    class12Percentage: 91.5,
    graduationCGPA: 8.90,
    activeBacklogs: false,
    activeBacklogsRaw: 'No',
    resumeUrl: 'https://example.com/resumes/sneha_reddy.pdf',
    stage: 'Stage 3',
    comments: [
      'Excellent embedded systems and C++ portfolio.',
      'Completed Stage 2 architectural round.',
    ],
  },
  {
    timestamp: '2024-03-02 14:45:00',
    emailAddress: 'arjun.nair@example.com',
    fullName: 'Arjun Nair',
    gender: 'Male',
    dob: '2002-09-30',
    contactNumber: '+91 98765 43214',
    emailId: 'arjun.nair@example.com',
    registrationNo: 'REG-2024-005',
    college: 'IIIT Jabalpur',
    course: 'B.Tech',
    passingYear: 2025,
    specialization: 'Computer Science and Engineering',
    class10Percentage: 88.0,
    class12Percentage: 84.5,
    graduationCGPA: 8.15,
    activeBacklogs: false,
    activeBacklogsRaw: 'No',
    resumeUrl: 'https://example.com/resumes/arjun_nair.pdf',
    stage: 'New',
    comments: [
      'Application received via college placement drive.',
    ],
  },
  {
    timestamp: '2024-03-03 10:00:22',
    emailAddress: 'ananya.gupta@example.com',
    fullName: 'Ananya Gupta',
    gender: 'Female',
    dob: '2003-04-12',
    contactNumber: '+91 98765 43215',
    emailId: 'ananya.gupta@example.com',
    registrationNo: 'REG-2024-006',
    college: 'IIT Roorkee',
    course: 'B.Tech',
    passingYear: 2026,
    specialization: 'Data Science and AI',
    class10Percentage: 97.2,
    class12Percentage: 95.8,
    graduationCGPA: 9.60,
    activeBacklogs: false,
    activeBacklogsRaw: 'No',
    resumeUrl: 'https://example.com/resumes/ananya_gupta.pdf',
    stage: 'Stage 3',
    comments: [
      'Outstanding machine learning background and research publication.',
      'Strong Python and PyTorch proficiency.',
    ],
  },
  {
    timestamp: '2024-03-03 15:10:05',
    emailAddress: 'vikram.singh@example.com',
    fullName: 'Vikram Singh',
    gender: 'Male',
    dob: '2001-07-25',
    contactNumber: '+91 98765 43216',
    emailId: 'vikram.singh@example.com',
    registrationNo: 'REG-2024-007',
    college: 'NIT Surathkal',
    course: 'B.Tech',
    passingYear: 2024,
    specialization: 'Mechanical Engineering',
    class10Percentage: 78.4,
    class12Percentage: 74.0,
    graduationCGPA: 6.95,
    activeBacklogs: true,
    activeBacklogsRaw: 'Yes (2 active backlogs)',
    resumeUrl: 'https://example.com/resumes/vikram_singh.pdf',
    stage: 'Rejected',
    comments: [
      'Did not meet minimum CGPA cutoff for software engineering role.',
      'Sent rejection letter.',
    ],
  },
  {
    timestamp: '2024-03-04 11:30:40',
    emailAddress: 'rohit.kulkarni@example.com',
    fullName: 'Rohit Kulkarni',
    gender: 'Male',
    dob: '2002-12-05',
    contactNumber: '+91 98765 43217',
    emailId: 'rohit.kulkarni@example.com',
    registrationNo: 'REG-2024-008',
    college: 'Pune Institute of Computer Technology',
    course: 'B.E.',
    passingYear: 2025,
    specialization: 'Information Technology',
    class10Percentage: 90.2,
    class12Percentage: 87.5,
    graduationCGPA: 8.40,
    activeBacklogs: false,
    activeBacklogsRaw: 'No',
    resumeUrl: 'https://example.com/resumes/rohit_kulkarni.pdf',
    stage: 'On Hold',
    comments: [
      'Awaiting candidate availability for Stage 2 interview scheduling.',
    ],
  },
  {
    timestamp: '2024-03-04 16:20:18',
    emailAddress: 'deepa.nambiar@example.com',
    fullName: 'Deepa Nambiar',
    gender: 'Female',
    dob: '2003-01-19',
    contactNumber: '+91 98765 43218',
    emailId: 'deepa.nambiar@example.com',
    registrationNo: 'REG-2024-009',
    college: 'IIIT Hyderabad',
    course: 'B.Tech',
    passingYear: 2025,
    specialization: 'Computer Science and Engineering',
    class10Percentage: 95.5,
    class12Percentage: 93.0,
    graduationCGPA: 9.10,
    activeBacklogs: false,
    activeBacklogsRaw: 'No',
    resumeUrl: 'https://example.com/resumes/deepa_nambiar.pdf',
    stage: 'Stage 1',
    comments: [
      'Passed initial screening resume assessment.',
    ],
  },
  {
    timestamp: '2024-03-05 09:15:55',
    emailAddress: 'karan.mehta@example.com',
    fullName: 'Karan Mehta',
    gender: 'Male',
    dob: '2002-06-11',
    contactNumber: '+91 98765 43219',
    emailId: 'karan.mehta@example.com',
    registrationNo: 'REG-2024-010',
    college: 'DTU Delhi',
    course: 'B.Tech',
    passingYear: 2025,
    specialization: 'Software Engineering',
    class10Percentage: 89.0,
    class12Percentage: 86.4,
    graduationCGPA: 8.25,
    activeBacklogs: false,
    activeBacklogsRaw: 'No',
    resumeUrl: 'https://example.com/resumes/karan_mehta.pdf',
    stage: 'Stage 2',
    comments: [
      'Great fullstack React and Node experience.',
    ],
  },
  {
    timestamp: '2024-03-05 13:40:02',
    emailAddress: 'tanya.sen@example.com',
    fullName: 'Tanya Sen',
    gender: 'Female',
    dob: '2003-03-27',
    contactNumber: '+91 98765 43220',
    emailId: 'tanya.sen@example.com',
    registrationNo: 'REG-2024-011',
    college: 'Jadavpur University',
    course: 'B.Tech',
    passingYear: 2026,
    specialization: 'Computer Science and Engineering',
    class10Percentage: 93.8,
    class12Percentage: 91.2,
    graduationCGPA: 8.85,
    activeBacklogs: false,
    activeBacklogsRaw: 'No',
    resumeUrl: 'https://example.com/resumes/tanya_sen.pdf',
    stage: 'New',
    comments: [],
  },
  {
    timestamp: '2024-03-05 17:05:40',
    emailAddress: 'mohit.joshi@example.com',
    fullName: 'Mohit Joshi',
    gender: 'Male',
    dob: '2001-10-14',
    contactNumber: '+91 98765 43221',
    emailId: 'mohit.joshi@example.com',
    registrationNo: 'REG-2024-012',
    college: 'NIT Trichy',
    course: 'B.Tech',
    passingYear: 2024,
    specialization: 'Electrical and Electronics',
    class10Percentage: 82.5,
    class12Percentage: 80.0,
    graduationCGPA: 7.60,
    activeBacklogs: false,
    activeBacklogsRaw: 'No',
    resumeUrl: 'https://example.com/resumes/mohit_joshi.pdf',
    stage: 'On Hold',
    comments: [
      'Followed up with candidate regarding joining timeline.',
    ],
  },
];

async function main() {
  const databaseUrl = process.env.DATABASE_URL || '';
  if (!databaseUrl.includes('workflow-test')) {
    throw new Error(
      'Sample seeding is blocked for the live database. Use a separate test DATABASE_URL containing "workflow-test".'
    );
  }

  console.log('Seeding SQLite database...');
  // Clear existing comments and students
  await prisma.comment.deleteMany({});
  await prisma.student.deleteMany({});

  for (const item of dummyStudents) {
    const { comments, ...studentData } = item;
    const student = await prisma.student.create({
      data: {
        ...studentData,
        comments: {
          create: comments.map((c) => ({ comment: c })),
        },
      },
    });
    console.log(`Created student: ${student.fullName} (${student.registrationNo}) [${student.stage}]`);
  }

  console.log('Seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error('Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
